name: 'Deploy wiki'
on:
  push:
    branches:
      # - master
      - feature/162-mkdocs
jobs:
  deploy_wiki:
    name: 'Deploy wiki'
#    if: startsWith(github.repository, 'codeoverflow-org') # don't run this in forks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install mkdocs
        run: |
          pip install mkdocs
          pip install mkdocs-material
      - name: Build docs
        run: |
          mkdocs build --clean
      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_PAT }}
          PUBLISH_DIR: ./site
          EXTERNAL_REPOSITORY: joblo2213/chatoverflow-gh-pages #codeoverflow-org/chatoverflow-gh-pages
          PUBLISH_BRANCH: master

# This file is not included in the wiki.
