name: 'Deploy wiki'
on:
  push:
    branches:
      - master
jobs:
  deploy_wiki:
    name: 'Deploy wiki'
    if: startsWith(github.repository, 'codeoverflow-org') # don't run this in forks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: codeoverflow-org/chatoverflow-gh-pages
          path: gh-pages
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Build dark-theme.css
        uses: gha-utilities/sass-build@v0.1.0
        with:
          source: docs/stylesheets/dark-theme.scss
          destination: docs/stylesheets/dark-theme.css
      - name: Build custom-header.css
        uses: gha-utilities/sass-build@v0.1.0
        with:
          source: docs/stylesheets/custom-header.scss
          destination: docs/stylesheets/custom-header.css
      - name: 'Fix links'
        run: bash .scripts/fix-links.sh
      - name: Build docs
        run: mkdocs build --clean
      - name: Copy preserved files
        run: bash .scripts/copy-preserved.sh
      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_DIR: ./site
          EXTERNAL_REPOSITORY: codeoverflow-org/chatoverflow-gh-pages
          PUBLISH_BRANCH: master